version: "2"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    env_file:
        - ./app/env/.env

  mysql:
    image: mariadb:10.3.4
    ports:
        - 3306:3306
    volumes:
        - ./data/mariadb:/var/lib/mysql
    env_file:
        - ./app/env/.env

